name: PlayerWarpGUI
version: 1.3.4
description: PlayerWarpGUI
author: judgetread
authors: [judgetread] 
website: http://thelasthero.net
main: PlayerWarpGUI.PlayerWarpGUI
softdepend: [GriefPrevention, worldguard, WorldGuard, RedProtect, Vault]
commands:
   playerwarps:
      description: Set and go to player warps.
      aliases: [pwarps, pwarp, playerwarp]  