name: PlayerWarpGUI
version: 0.1
description: PlayerWarpGUI
author: judgetread
authors: [judgetread] 
website: http://thelasthero.net
main: PlayerWarpGUI.PlayerWarpGUI
softdepend: [GriefPrevention, worldguard, WorldGuard, RedProtect, Vault, Residence, Factions, MassiveCore]
commands:
  pwarps:
    description: Set and go to player warps.
    aliases: [pwarp]