#################################################
# +-------------------------------------------+ #
# |   config.YML Revision 06 by Judgetread    | #
# +-------------------------------------------+ #
#################################################

# +----------+#
# | Messages |#
# +----------+#
# prefix: Text that will be displayed before every message sent
#         from this plugin.
Messages:
  prefix: '&6[&aPlayerWarpGUI&6] &f'
  language: 'en_US'
  
Teleport:
  cooldown: 3
  cancelOnMovement: true
  godModeAfterTP: 0
  

Metrics:
  enabled: true